# Generated by Django 4.2.4 on 2023-08-20 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entry', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveSmallIntegerField(default=18)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], default='male', max_length=6)),
                ('phone', models.CharField(max_length=15)),
                ('village', models.CharField(max_length=100)),
                ('type_id', models.CharField(choices=[('aadhar', 'aadhar'), ('voterId', 'voterId'), ('drivingLicense', 'drivingLicense'), ('passport', 'passport'), ('other', 'other')], default='aadhar', max_length=20)),
                ('number_id', models.CharField(max_length=50)),
                ('family_members', models.PositiveSmallIntegerField(default=0)),
                ('position', models.CharField(choices=[('main', 'main'), ('waiting', 'waiting')], default='main', max_length=7)),
                ('status', models.CharField(choices=[('cancelled', 'cancelled'), ('live', 'live')], default='live', max_length=9)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hawan.district')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hawan.event')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hawan.province')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], default='', max_length=6)),
                ('age', models.PositiveSmallIntegerField(default=1)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hawan.participant')),
            ],
        ),
        migrations.CreateModel(
            name='EventManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distric_province', to='hawan.province'),
        ),
    ]
